CREATE DATABASE gora;
USE gora;

CREATE TABLE gora (
    id INT AUTO_INCREMENT PRIMARY KEY,
    event_namn VARCHAR(50) NOT NULL,
    plats VARCHAR(100) NOT NULL,
    datum DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);